# This file was generated by GoReleaser. DO NOT EDIT.
cask "evcc" do
  version "0.316.0"

  on_macos do
    sha256 "55e09324ea4a26a4604553d6dd284fbab386a9a2cef0ec329427bc35d858effc"
    url "https://github.com/evcc-io/evcc/releases/download/#{version}/evcc_#{version}_macOS-all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "824dd1e5937f68221de0aabd7ba0f3ba637f913c2a098a1e5306e5c300a74295"
      url "https://github.com/evcc-io/evcc/releases/download/#{version}/evcc_#{version}_linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "8fd76e9d57ecf757ef5d448dc45ad61daf674974d0aec6182ed4ae4dbb23ac74"
      url "https://github.com/evcc-io/evcc/releases/download/#{version}/evcc_#{version}_linux-amd64.tar.gz"
    end
  end

  name "evcc"
  desc "Sonne tanken ☀️🚘"
  homepage "https://evcc.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "evcc"

  # No zap stanza required
end
