# This file was generated by GoReleaser. DO NOT EDIT.
cask "evcc" do
  version "0.315.2"

  on_macos do
    sha256 "bf877588944fe103a4ecfda751f41a00154c09ae4a0b7d3939af011b1e3b9cfa"
    url "https://github.com/evcc-io/evcc/releases/download/#{version}/evcc_#{version}_macOS-all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "9947382522c754279d19e7c7106834115d6c9afbeaefed1a1ed1066c33654668"
      url "https://github.com/evcc-io/evcc/releases/download/#{version}/evcc_#{version}_linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "24f202847d22074e1a40d9716700340ee2806d5b14bb3444f8081494c3ef9c7f"
      url "https://github.com/evcc-io/evcc/releases/download/#{version}/evcc_#{version}_linux-amd64.tar.gz"
    end
  end

  name "evcc"
  desc "Sonne tanken ☀️🚘"
  homepage "https://evcc.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "evcc"

  # No zap stanza required
end
