# This file was generated by GoReleaser. DO NOT EDIT.
cask "evcc" do
  version "0.315.0"

  on_macos do
    sha256 "31b148fa4d4c776e26f706c62f686aa56d2bc97e0887e4598a6db69a13c7d495"
    url "https://github.com/evcc-io/evcc/releases/download/#{version}/evcc_#{version}_macOS-all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "5ff65e9420997b3d23835da8de81e806c87e862bc9a6417ef61d814292623f5a"
      url "https://github.com/evcc-io/evcc/releases/download/#{version}/evcc_#{version}_linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "7112e5718e76e28e89f7e3ce392340eca5d543293fdd8953bbaf520b38f01217"
      url "https://github.com/evcc-io/evcc/releases/download/#{version}/evcc_#{version}_linux-amd64.tar.gz"
    end
  end

  name "evcc"
  desc "Sonne tanken ☀️🚘"
  homepage "https://evcc.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "evcc"

  # No zap stanza required
end
