# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Evcc < Formula
  desc "Sonne tanken ☀️🚘"
  homepage "https://evcc.io"
  version "0.122.0"
  license "MIT"

  on_macos do
    url "https://github.com/evcc-io/evcc/releases/download/0.122.0/evcc_0.122.0_macOS-all.tar.gz"
    sha256 "466c6366fb70eada7000c46159503b03cba9ad7dfed72ddc7b3efb22acbe2b0b"

    def install
      bin.install "evcc"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/evcc-io/evcc/releases/download/0.122.0/evcc_0.122.0_linux-armv6.tar.gz"
      sha256 "c3c4948d870264f701da2503be362772465a6785233e5da30fe8a000c2360d24"

      def install
        bin.install "evcc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/evcc-io/evcc/releases/download/0.122.0/evcc_0.122.0_linux-amd64.tar.gz"
      sha256 "271d2afc8009978f279976030a9130edefd57ce0ecaa43b6a2acae20ef1de530"

      def install
        bin.install "evcc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evcc-io/evcc/releases/download/0.122.0/evcc_0.122.0_linux-arm64.tar.gz"
      sha256 "a40e6a3150921625e3ab9521cca558caba75af1a59db4ad7b704df47368e0775"

      def install
        bin.install "evcc"
      end
    end
  end

  service do
    run [opt_bin/"evcc"]
    working_dir HOMEBREW_PREFIX
    keep_alive true
    log_path var/"log/evcc.log"
    error_log_path var/"log/evcc.log"
  end

  test do
    system "#{bin}/evcc --version"
  end
end
