# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Evcc < Formula
  desc "Sonne tanken ☀️🚘"
  homepage "https://evcc.io"
  version "0.128.1"
  license "MIT"

  on_macos do
    url "https://github.com/evcc-io/evcc/releases/download/0.128.1/evcc_0.128.1_macOS-all.tar.gz"
    sha256 "33e83836341a479138b995daf2ffd0c8623e98bfba3bf93f3e4a733073d38cd9"

    def install
      bin.install "evcc"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evcc-io/evcc/releases/download/0.128.1/evcc_0.128.1_linux-amd64.tar.gz"
        sha256 "d1cdbcb5d18d410126ee73d6a2689f6b00b994add7de5b9bfc3246150589052b"

        def install
          bin.install "evcc"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/evcc-io/evcc/releases/download/0.128.1/evcc_0.128.1_linux-armv6.tar.gz"
        sha256 "6ed7c87d1a2352001c3bc2f3385573fa1c7be663900ae62e1bbb3a4ded258573"

        def install
          bin.install "evcc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evcc-io/evcc/releases/download/0.128.1/evcc_0.128.1_linux-arm64.tar.gz"
        sha256 "13804ac2206c9213492afbdaa93f49e5dc18df7a3c993a19e92b8fb5fa19ee67"

        def install
          bin.install "evcc"
        end
      end
    end
  end

  service do
    run [opt_bin/"evcc"]
    working_dir HOMEBREW_PREFIX
    keep_alive true
    log_path var/"log/evcc.log"
    error_log_path var/"log/evcc.log"
  end

  test do
    system "#{bin}/evcc --version"
  end
end
