# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Evcc < Formula
  desc "Sonne tanken ☀️🚘"
  homepage "https://evcc.io"
  version "0.126.6"
  license "MIT"

  on_macos do
    url "https://github.com/evcc-io/evcc/releases/download/0.126.6/evcc_0.126.6_macOS-all.tar.gz"
    sha256 "b7fefadc4c8bc76580be96fe453151192f4f37371bbce1981ebeff1c8f20b69e"

    def install
      bin.install "evcc"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evcc-io/evcc/releases/download/0.126.6/evcc_0.126.6_linux-amd64.tar.gz"
        sha256 "c7fc281b8ed61fdc1a9af3476bcf08bbdcae3d074fc5c4c50b35c7c8b8dbe418"

        def install
          bin.install "evcc"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/evcc-io/evcc/releases/download/0.126.6/evcc_0.126.6_linux-armv6.tar.gz"
        sha256 "100660ff23759a4dc9f383d7f433d1b0a898ca0b3ff69464bd596d198b1e2c21"

        def install
          bin.install "evcc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evcc-io/evcc/releases/download/0.126.6/evcc_0.126.6_linux-arm64.tar.gz"
        sha256 "ca5f564c8342373fb1f86ee3707e8e72daa86a1354c1657df8224a2ee2c17935"

        def install
          bin.install "evcc"
        end
      end
    end
  end

  service do
    run [opt_bin/"evcc"]
    working_dir HOMEBREW_PREFIX
    keep_alive true
    log_path var/"log/evcc.log"
    error_log_path var/"log/evcc.log"
  end

  test do
    system "#{bin}/evcc --version"
  end
end
